version: '3.7'

services:
  backend:
    container_name: backend
    image: backend_image
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        CORS_IP: ${CORS_IP}
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    image: frontend_image
    build: 
      context: ./vue-frontend
      dockerfile: Dockerfile
    volumes:
      - ./vue-frontend:/app
      - /app/node_modules
    ports:
      - "80:5173"
    

networks:
  default:
    external: true
    name: app_main